name: Build S24Ultra-Spoofer_LSPosed APK

on:
  workflow_dispatch:
    
  
jobs:
  pre_build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to create releases and upload assets
      packages: write  # Required if you're working with packages
      actions: read    # Required to read workflow details

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/*.apk
          name: "${{ env.APP_NAME }}"
          tag_name: "${{ env.TAG_NAME }}"
          body: |
            Automated build of ${{ env.APP_NAME }}
            Build number: ${{ github.run_number }}
            Commit: ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
